#pragma once
#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace GameplayCameraTags {
	// camera style
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Style_Close);
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Style_Balanced);
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Style_Far);
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Style_Combat);

	// mode
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mode_Freecam);
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mode_Strafe);
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mode_Aim);

	// view mode
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(View_Third);
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(View_First);

	// shoulder side
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shoulder_Right);
	CAMERASYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shoulder_Left);
}